---
language: go

go:
  - 1.8.3
  - tip

services:
  - docker

install:
  - go get github.com/golang/lint/golint
  - go get github.com/FiloSottile/vendorcheck
  # Install gometalinter and certain linters
  - go get github.com/alecthomas/gometalinter
  - go get github.com/client9/misspell/cmd/misspell
  - go get github.com/gordonklaus/ineffassign
  - go get golang.org/x/tools/cmd/goimports
  - go get github.com/tsenart/deadcode

script:
  - make lint
  - vendorcheck ./...
  - make ci

after_script:
  # TODO: When Go 1.9 is released, replace $(go list) subcommand with ./... because vendor folder should be ignored
  - golint $(go list ./... | grep -v vendor)
